version: '2'
services:
  uvsconventions-app:
    image: uvsconventions
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://uvsconventions-mysql:3306/uvsconventions?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://uvsconventions-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://uvsconventions-elasticsearch:9200
    ports:
      - 8080:8080
  uvsconventions-mysql:
    extends:
      file: mysql.yml
      service: uvsconventions-mysql
  uvsconventions-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: uvsconventions-elasticsearch
